"use client";
import { useState } from "react";
import { api, send } from "@/lib/api";
import type { AIProjectPlan, Challenge, Project } from "@/lib/types";
import { usePortal } from "./providers";
import { ActionButton, Badge, DateText, Field, Money, MutationForm, Panel, Select, Textarea, formObject } from "./ui";

export function DecisionForm({ path, onDone, defaultNote = "" }: { path: string; onDone: () => void; defaultNote?: string }) { const { t } = usePortal(); return <MutationForm submit="save_decision" onSubmit={data => send(path, formObject(data))} onDone={onDone}><Select label="decision" name="decision"><option value="approve">{t("approve")}</option><option value="request_changes">{t("request_changes")}</option></Select><Textarea label="note" name="note" required minLength={3} maxLength={2000} rows={2} defaultValue={defaultNote} /></MutationForm>; }

export function SupportForm({ projectId, onDone }: { projectId: string; onDone: () => void }) {
  const { t } = usePortal(); const [kind, setKind] = useState("mentorship");
  return <MutationForm submit="offer_support" onDone={onDone} onSubmit={data => { const raw = formObject(data); return send(`/projects/${projectId}/partnerships`, { ...raw, amount: Number(raw.amount || 0) }); }}><Select label="kind" name="kind" value={kind} onChange={e => setKind(e.target.value)}>{["mentorship", "funding", "prototyping", "pilot", "technology_transfer"].map(k => <option key={k} value={k}>{t(k)}</option>)}</Select><Textarea label="support_description" name="description" required minLength={20} maxLength={4000} />{kind === "funding" && <Field label="amount" name="amount" type="number" required min={0.01} max={999999999999.99} step="0.01" />}<p className="muted small">{t("funding_note")}</p></MutationForm>;
}

export function ProjectPanels({ project: p, challenge: c, refresh }: { project: Project; challenge: Challenge; refresh: () => void }) {
  const { t, user, lang } = usePortal(); const coordinator = user?.role === "university" && user.organization_id === p.university_id; const gov = user?.role === "government"; const editable = coordinator && ["assigned", "in_progress"].includes(c.status);
  const proposalEditable = coordinator && c.status === "assigned" && (!p.proposal || p.proposal.status === "changes_requested");
  const outcomeEditable = coordinator && c.status === "in_progress" && p.milestones.length > 0 && p.milestones.every(m => m.status === "approved");
  const [plan, setPlan] = useState<AIProjectPlan>(); const [planVersion, setPlanVersion] = useState(0); const [reviewNote, setReviewNote] = useState(""); const [reviewVersion, setReviewVersion] = useState(0);
  return <>
    {coordinator && ["assigned", "in_progress"].includes(c.status) && <Panel title="ai_plan_title" hint="ai_plan_copy"><ActionButton action={async () => setPlan(await send<AIProjectPlan>(`/projects/${p.id}/ai-plan?language=${lang}`, {}))}>{t("generate_plan")}</ActionButton>{plan && <div className="ai-suggestions"><p className="prose">{plan.approach}</p><p><strong>{t("duration_weeks")}:</strong> {plan.duration_weeks}</p><h3>{t("suggested_milestones")}</h3><ul>{plan.milestones.map(m => <li key={`${m.week}-${m.title}`}>{m.title} · {t("target_week")} {m.week}</li>)}</ul>{proposalEditable && <button className="button secondary" type="button" onClick={() => setPlanVersion(v => v + 1)}>{t("use_plan")}</button>}</div>}</Panel>}
    <Panel title="team" hint={coordinator ? "team_hint" : undefined}><div className="member-list">{p.team.map(member => <div className="member" key={member.id}><span className="avatar small-avatar">{member.name.slice(0, 1)}</span><div><strong>{member.name}</strong><small>{t(member.kind)} · {member.discipline}</small></div>{editable && <ActionButton variant="quiet" action={() => api(`/projects/${p.id}/team/${member.id}`, { method: "DELETE" })} onDone={refresh}>{t("remove")}</ActionButton>}</div>)}</div>{editable && <details className="disclosure"><summary>{t("add_member")}</summary><MutationForm submit="add_member" reset onDone={refresh} onSubmit={data => send(`/projects/${p.id}/team`, formObject(data))}><div className="form-row"><Field label="name" name="name" required minLength={2} maxLength={120} /><Field label="discipline" name="discipline" required minLength={2} maxLength={120} /></div><Select label="kind" name="kind"><option value="student">{t("student")}</option><option value="faculty">{t("faculty")}</option></Select></MutationForm></details>}</Panel>
    <Panel title="proposal">{p.proposal ? <><div className="inline-meta"><Badge value={p.proposal.status} /><span><Money value={p.proposal.budget} /></span><span>{p.proposal.duration_weeks} {t("duration_weeks")}</span></div><p className="prose">{p.proposal.approach}</p>{p.proposal.review_note && <p className="notice">{p.proposal.review_note}</p>}</> : <p className="muted">{t("no_proposal")}</p>}{proposalEditable && <MutationForm key={`${p.proposal?.id || "new"}-${planVersion}`} submit="submit_proposal" onDone={refresh} onSubmit={data => { const raw = formObject(data); return send(`/projects/${p.id}/proposal`, { ...raw, budget: Number(raw.budget), duration_weeks: Number(raw.duration_weeks) }, "PUT"); }}><Textarea label="approach" name="approach" required minLength={30} maxLength={10000} defaultValue={plan?.approach || p.proposal?.approach} /><div className="form-row"><Field label="budget" name="budget" type="number" required min={0} max={999999999999.99} step="0.01" defaultValue={p.proposal?.budget} /><Field label="duration_weeks" name="duration_weeks" type="number" required min={1} max={520} defaultValue={plan?.duration_weeks || p.proposal?.duration_weeks || 12} /></div></MutationForm>}{gov && p.proposal?.status === "submitted" && <DecisionForm path={`/projects/${p.id}/proposal/review`} onDone={refresh} />}</Panel>
    <Panel title="milestones"><div className="milestone-list">{p.milestones.map((m, i) => <article className="milestone" key={m.id}><div className="milestone-heading"><span className="step-marker">{i + 1}</span><div><h3>{m.title}</h3><small>{t("due_date")}: <DateText value={m.due_date + "T12:00:00"} /></small></div><Badge value={m.status} /></div>{m.evidence && <p className="prose">{m.evidence}</p>}{m.review_note && <p className="notice">{m.review_note}</p>}{coordinator && c.status === "in_progress" && ["pending", "changes_requested"].includes(m.status) && <MutationForm submit="submit_evidence" onDone={refresh} onSubmit={data => send(`/milestones/${m.id}/submit`, formObject(data))}><Textarea label="testing_evidence" name="evidence" required minLength={20} maxLength={10000} defaultValue={m.evidence} /></MutationForm>}{gov && m.status === "submitted" && <DecisionForm path={`/milestones/${m.id}/review`} onDone={refresh} />}</article>)}</div>{!p.milestones.length && <p className="muted">{t(c.status === "assigned" ? "no_milestones" : "no_milestones_yet")}</p>}{coordinator && c.status === "in_progress" && <details className="disclosure"><summary>{t("add_milestone")}</summary><MutationForm submit="add_milestone" onDone={refresh} reset onSubmit={data => send(`/projects/${p.id}/milestones`, formObject(data))}><Field label="milestone_title" name="title" required minLength={3} maxLength={180} /><Field label="due_date" name="due_date" type="date" required /></MutationForm></details>}</Panel>
    <Panel title="partnerships">{p.partnerships.length ? p.partnerships.map(offer => <article className="offer" key={offer.id}><div className="row-between"><h3>{offer.organization_name}</h3><Badge value={offer.status} /></div><p className="muted">{t(offer.kind)} {offer.kind === "funding" && <>· <Money value={offer.amount} /></>}</p><p className="prose">{offer.description}</p>{coordinator && offer.status === "offered" && ["assigned", "in_progress"].includes(c.status) && <div className="button-row"><ActionButton action={() => send(`/partnerships/${offer.id}/review`, { decision: "accept" })} onDone={refresh}>{t("accept")}</ActionButton><ActionButton variant="quiet" action={() => send(`/partnerships/${offer.id}/review`, { decision: "decline" })} onDone={refresh}>{t("decline")}</ActionButton></div>}</article>) : <p className="muted">{t("no_partners")}</p>}<p className="muted small">{t("funding_note")}</p></Panel>
    <Panel title="outcome" hint={coordinator ? "outcome_hint" : undefined}>
      {p.outcome ? <><Badge value={p.outcome.status} /><div className="metric-row"><div><strong>{p.outcome.beneficiaries}</strong><span>{t("beneficiaries")}</span></div><div><strong>{p.outcome.baseline} → {p.outcome.result}</strong><span>{p.outcome.metric} ({p.outcome.unit})</span></div></div><p className="prose">{p.outcome.testing_evidence}</p><div className="inline-meta"><span>{t("patents")}: {p.outcome.patents}</span><span>{t("startups")}: {p.outcome.startups}</span></div>{p.outcome.innovation_details && <p className="prose">{p.outcome.innovation_details}</p>}{p.outcome.review_note && <p className="notice">{p.outcome.review_note}</p>}{p.outcome.citizen_feedback && <blockquote><strong>{t("community_feedback")}</strong><p>{p.outcome.citizen_feedback}</p></blockquote>}</> : <p className="muted">{t("no_outcome")}</p>}
      {outcomeEditable && <details className="disclosure"><summary>{t("submit_outcome")}</summary><MutationForm submit="submit_outcome" onDone={refresh} onSubmit={data => { const raw: Record<string, string | number> = formObject(data); ["beneficiaries", "baseline", "result", "patents", "startups"].forEach(k => { raw[k] = Number(raw[k] || 0); }); return send(`/projects/${p.id}/outcome`, raw, "PUT"); }}><Field label="beneficiaries" name="beneficiaries" type="number" required min={0} max={100000000} defaultValue={p.outcome?.beneficiaries} /><div className="form-row"><Field label="metric" name="metric" required minLength={3} maxLength={180} defaultValue={p.outcome?.metric} /><Field label="unit" name="unit" required maxLength={60} defaultValue={p.outcome?.unit} /></div><div className="form-row"><Field label="baseline" name="baseline" type="number" required step="any" defaultValue={p.outcome?.baseline} /><Field label="result" name="result" type="number" required step="any" defaultValue={p.outcome?.result} /></div><Textarea label="testing_evidence" name="testing_evidence" required minLength={30} maxLength={10000} defaultValue={p.outcome?.testing_evidence} /><div className="form-row"><Field label="patents" name="patents" type="number" min={0} max={10000} defaultValue={p.outcome?.patents || 0} /><Field label="startups" name="startups" type="number" min={0} max={10000} defaultValue={p.outcome?.startups || 0} /></div><Textarea label="innovation_details" name="innovation_details" maxLength={4000} defaultValue={p.outcome?.innovation_details} /></MutationForm></details>}
      {gov && p.outcome?.status === "submitted" && <div className="ai-suggestions"><h3>{t("ai_outcome_title")}</h3><p className="muted small">{t("ai_outcome_copy")}</p><div className="row-between"><Badge value={p.outcome.ai_status || "pending"} /><ActionButton action={() => send(`/projects/${p.id}/outcome/analyze`, {})} onDone={refresh}>{t("analyze_outcome")}</ActionButton></div>{p.outcome.ai_status === "unavailable" && <p className="notice">{t("ai_unavailable")}</p>}{p.outcome.ai_suggestions && <div className="stack compact-stack"><p><strong>{t("recommended_action")}:</strong> {t(p.outcome.ai_suggestions.recommendation)}</p><p>{lang === "hi" ? p.outcome.ai_suggestions.reason_hi : p.outcome.ai_suggestions.reason_en}</p>{p.outcome.ai_suggestions.evidence_gaps.length > 0 && <div><strong>{t("evidence_gaps")}</strong><ul>{p.outcome.ai_suggestions.evidence_gaps.map(x => <li key={x}>{x}</li>)}</ul></div>}{p.outcome.ai_suggestions.metric_observations.length > 0 && <div><strong>{t("metric_observations")}</strong><ul>{p.outcome.ai_suggestions.metric_observations.map(x => <li key={x}>{x}</li>)}</ul></div>}<button type="button" className="button secondary" onClick={() => { setReviewNote(lang === "hi" ? p.outcome!.ai_suggestions!.reason_hi : p.outcome!.ai_suggestions!.reason_en); setReviewVersion(v => v + 1); }}>{t("use_review_note")}</button></div>}</div>}
      {gov && p.outcome?.status === "submitted" && <DecisionForm key={reviewVersion} path={`/projects/${p.id}/outcome/review`} onDone={refresh} defaultNote={reviewNote} />}
      {user?.id === c.owner_id && p.outcome && <details className="disclosure"><summary>{t("community_feedback")}</summary><p className="muted">{t("feedback_hint")}</p><MutationForm submit="save_feedback" onDone={refresh} onSubmit={data => send(`/projects/${p.id}/feedback`, formObject(data), "PUT")}><Textarea label="community_feedback" name="body" required maxLength={4000} defaultValue={p.outcome.citizen_feedback} /></MutationForm></details>}
    </Panel>
  </>;
}
