"use client";
import Link from "next/link";
import Image from "next/image";
import { ArrowRight, ArrowUpRight, MapPin, Lightbulb, Handshake, UsersThree, GraduationCap, Buildings, ShieldCheck, Leaf } from "@phosphor-icons/react";
import { useState } from "react";
import { useResource } from "@/lib/api";
import type { Analytics, Challenge, Organization } from "@/lib/types";
import { usePortal } from "./providers";
import { Badge, ChallengeCard, DateText, Empty, ErrorBox, Loading, Panel, Progress, Select } from "./ui";
import { SupportForm } from "./project-forms";

export function HomePage() {
  const { t, user } = usePortal(); const stats = useResource<Analytics>("/public/analytics"); const challenges = useResource<Challenge[]>("/public/challenges?limit=3");
  return <main id="main" className="home-page"><section className="hero container"><div className="hero-content"><div className="eyebrow"><span className="eyebrow-line" />{t("hero_eyebrow")}</div><h1>{t("hero_title_1")}<br /><span>{t("hero_title_2")}</span></h1><p>{t("hero_copy")}</p><div className="hero-actions"><Link href={user ? "/workspace/new" : "/register"} className="button primary large">{t("submit_challenge")}<ArrowRight size={20} /></Link><Link href="/challenges" className="text-link">{t("explore")}<ArrowUpRight size={20} /></Link></div></div><div className="hero-visual"><Image src="/forest.jpg" alt={t("hero_photo_alt")} width={960} height={1100} sizes="(max-width: 580px) calc(100vw - 44px), (max-width: 1240px) 45vw, 533px" preload /><div className="hero-image-caption"><Leaf size={30} weight="duotone" /><p>{t("hero_caption")}</p></div><div className="image-corner" aria-hidden="true"><ArrowUpRight size={42} weight="light" /></div></div></section>
    <section className="stats-strip container" aria-label={t("analytics")}>{stats.error ? <ErrorBox code={stats.error} retry={stats.refresh} /> : ["challenges", "universities", "resolved", "beneficiaries"].map(key => <div key={key} className="stat"><strong>{stats.data ? (stats.data[key as keyof Analytics] as number).toLocaleString("en-IN") : <span className="skeleton inline-skeleton" />}</strong><span>{t(key)}</span></div>)}</section>
    <section className="community-section section-space"><div className="container"><div className="section-heading"><div><h2>{t("community_title")}</h2><p>{t("community_copy")}</p></div><Link href="/challenges" className="text-link">{t("view_all")}<ArrowRight size={19} /></Link></div>{challenges.error ? <ErrorBox code={challenges.error} retry={challenges.refresh} /> : challenges.loading ? <Loading /> : challenges.data?.length ? <div className="challenge-grid">{challenges.data.map(c => <ChallengeCard key={c.id} challenge={c} />)}</div> : <Empty />}</div></section>
    <section id="how-it-works" className="container section-space process-section"><div className="section-heading"><h2>{t("process_title")}</h2></div><div className="process-grid">{[{ n: "01", title: "step1_title", copy: "step1_copy", icon: Lightbulb }, { n: "02", title: "step2_title", copy: "step2_copy", icon: Handshake }, { n: "03", title: "step3_title", copy: "step3_copy", icon: Leaf }].map(s => <article key={s.n}><div className="process-top"><s.icon size={28} weight="duotone" /><span>{s.n}</span></div><h3>{t(s.title)}</h3><p>{t(s.copy)}</p></article>)}</div></section>
    <section id="impact" className="impact-section section-space"><div className="container impact-layout"><div className="impact-intro"><div className="eyebrow"><span className="eyebrow-line" />{t("impact_eyebrow")}</div><h2>{t("home_impact_title")}</h2><p>{t("home_impact_copy")}</p><Link href="/challenges" className="text-link">{t("impact_link")}<ArrowRight size={19} /></Link></div><div className="impact-list">{[{ n: "01", title: "impact_review_title", copy: "impact_review_copy", icon: ShieldCheck }, { n: "02", title: "impact_collab_title", copy: "impact_collab_copy", icon: Handshake }, { n: "03", title: "impact_outcome_title", copy: "impact_outcome_copy", icon: Leaf }].map(item => <article key={item.n} className="impact-item"><div className="impact-icon"><item.icon size={24} weight="duotone" /></div><div><h3>{t(item.title)}</h3><p>{t(item.copy)}</p></div><span className="impact-number">{item.n}</span></article>)}</div></div></section>
    <section id="faq" className="faq-section section-space"><div className="container faq-layout"><div className="faq-intro"><div className="eyebrow"><span className="eyebrow-line" />{t("faq_eyebrow")}</div><h2>{t("faq_title")}</h2><p>{t("faq_copy")}</p></div><div className="faq-list">{[1, 2, 3, 4, 5].map(n => <details key={n}><summary>{t(`faq_q${n}`)}</summary><p>{t(`faq_a${n}`)}</p></details>)}</div></div></section>
    <section id="ecosystem" className="ecosystem-section"><div className="container ecosystem-layout"><div><h2>{t("ecosystem_title")}</h2><p>{t("ecosystem_copy")}</p><Link href="/register" className="button primary">{t("register")}<ArrowRight size={18} /></Link></div><div className="ecosystem-grid">{[{ key: "citizen", icon: UsersThree }, { key: "university", icon: GraduationCap }, { key: "industry", icon: Buildings }, { key: "government", icon: ShieldCheck }].map(x => <div key={x.key}><x.icon size={32} weight="duotone" /><span>{t(x.key)}</span></div>)}</div></div></section></main>;
}

export function ExplorePage() {
  const { t } = usePortal(); const [query, setQuery] = useState(""); const [page, setPage] = useState(0); const metadata = useResource<{ districts: string[]; domains: string[] }>("/metadata");
  const list = useResource<Challenge[]>(`/public/challenges?${query}&offset=${page * 12}&limit=12`);
  return <main id="main" className="container page-space"><div className="page-heading"><div className="eyebrow">{t("explore")}</div><h1>{t("explore_title")}</h1><p>{t("explore_copy")}</p></div><form className="filter-bar" onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); setQuery(new URLSearchParams(Object.fromEntries(data) as Record<string, string>).toString()); setPage(0); }}><div className="field search-field"><label htmlFor="q">{t("search")}</label><input id="q" name="q" type="search" placeholder={t("search_placeholder")} maxLength={100} /></div><Select label="district" name="district"><option value="">{t("all_districts")}</option>{metadata.data?.districts.map(d => <option key={d} value={d}>{t(d)}</option>)}</Select><Select label="domain" name="domain"><option value="">{t("all_domains")}</option>{metadata.data?.domains.map(d => <option key={d} value={d}>{t(d)}</option>)}</Select><Select label="status" name="status"><option value="">{t("all_statuses")}</option>{["validated", "assigned", "in_progress", "validation", "resolved"].map(s => <option key={s} value={s}>{t(s)}</option>)}</Select><button className="button primary" type="submit">{t("filter")}</button></form>{metadata.error && <ErrorBox code={metadata.error} retry={metadata.refresh} />}{list.loading ? <Loading /> : list.error ? <ErrorBox code={list.error} retry={list.refresh} /> : list.data?.length ? <div className="challenge-grid">{list.data.map(c => <ChallengeCard key={c.id} challenge={c} />)}</div> : <Empty />}<div className="pagination"><button className="button secondary" disabled={page === 0 || list.loading} onClick={() => setPage(p => p - 1)}>{t("previous")}</button><span>{t("page")} {page + 1}</span><button className="button secondary" disabled={list.loading || (list.data?.length || 0) < 12} onClick={() => setPage(p => p + 1)}>{t("next")}</button></div></main>;
}

export function PublicDetail({ id }: { id: string }) {
  const { t, lang, user } = usePortal(); const detail = useResource<Challenge>(`/public/challenges/${id}`); const [offered, setOffered] = useState(false);
  if (detail.loading) return <main id="main" className="container page-space"><Loading /></main>;
  if (detail.error || !detail.data) return <main id="main" className="container page-space"><ErrorBox code={detail.error || "not_found"} retry={detail.refresh} /></main>;
  const c = detail.data;
  return <main id="main" className="container page-space"><Link href="/challenges" className="text-link back-link">← {t("explore")}</Link><div className="page-heading detail-heading"><div className="inline-meta"><span className="domain-tag">{t(c.domain)}</span><Badge value={c.status} /></div><h1>{lang === "hi" ? c.public_title_hi : c.public_title_en}</h1><div className="inline-meta"><span><MapPin size={16} />{t(c.district)}</span><span>{t("submitted_on")} <DateText value={c.created_at} /></span></div></div><div className="detail-grid"><div className="stack"><Panel title="public_summary"><p className="prose">{lang === "hi" ? c.summary_hi : c.summary_en}</p><div className="notice"><ShieldCheck size={22} /><p>{t("privacy_note")}</p></div></Panel>{c.status === "resolved" && <Panel title="outcome"><div className="metric-row">{["beneficiaries", "patents", "startups"].map(k => <div key={k}><strong>{c[k as "beneficiaries" | "patents" | "startups"]}</strong><span>{t(k)}</span></div>)}</div></Panel>}{c.project_id && ["assigned", "in_progress"].includes(c.status) && <Panel title="support_challenge">{user?.role === "industry" ? offered ? <p role="status" className="success-text">{t("offered")}</p> : <SupportForm projectId={c.project_id} onDone={() => setOffered(true)} /> : <><p className="muted">{t("sign_in_support")}</p><Link href="/login" className="button secondary">{t("sign_in")}<ArrowRight size={18} /></Link></>}</Panel>}{user && <Link href={`/workspace/challenges/${c.id}`} className="text-link">{t("open_workspace")}<ArrowRight /></Link>}</div><aside className="stack"><Panel title="progress"><Progress status={c.status} /></Panel><Panel title="lead_institution"><p>{c.university_name || t("awaiting_assignment")}</p></Panel></aside></div></main>;
}
