"use client";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, MapPin, WarningCircle, CheckCircle, Tray, Drop, Plant, Heartbeat, BookOpen, Tree, Lightning, Buildings, Wheelchair, UsersThree, Briefcase, Recycle, type Icon } from "@phosphor-icons/react";
import { useEffect, useId, useRef, useState, type ReactNode, type InputHTMLAttributes, type SelectHTMLAttributes, type TextareaHTMLAttributes } from "react";
import { ApiError } from "@/lib/api";
import type { Challenge } from "@/lib/types";
import { usePortal } from "./providers";

const domainIcons: Record<string, Icon> = { water: Drop, agriculture: Plant, healthcare: Heartbeat, education: BookOpen, environment: Tree, energy: Lightning, urban_development: Buildings, accessibility: Wheelchair, public_administration: UsersThree, rural_livelihoods: Briefcase, sanitation: Recycle };
export function DomainIcon({ domain, size = 22 }: { domain: string; size?: number }) { const Glyph = domainIcons[domain] || Plant; return <Glyph size={size} weight="duotone" aria-hidden="true" />; }
export function Badge({ value }: { value: string }) { const { t } = usePortal(); return <span className={`badge badge-${value}`}><span aria-hidden="true" className="status-dot" />{t(value)}</span>; }
export function ErrorBox({ code, retry }: { code: string; retry?: () => void }) { const { t } = usePortal(); return <div role="alert" className="notice error"><WarningCircle size={22} aria-hidden="true" /><div><p>{t(code)}</p>{retry && <button type="button" className="text-link" onClick={retry}>{t("retry")} <ArrowRight aria-hidden="true" /></button>}</div></div>; }
export function Loading() { const { t } = usePortal(); return <div role="status" aria-label={t("loading")} className="skeleton-group"><div className="skeleton skeleton-heading" /><div className="skeleton" /><div className="skeleton" /><span className="sr-only">{t("loading")}</span></div>; }
export function Empty({ title = "no_challenges", copy = "no_challenges_copy", children }: { title?: string; copy?: string; children?: ReactNode }) { const { t } = usePortal(); return <div className="empty"><Tray size={36} weight="duotone" aria-hidden="true" /><h3>{t(title)}</h3><p>{t(copy)}</p>{children}</div>; }
export function Field({ label, hint, ...props }: InputHTMLAttributes<HTMLInputElement> & { label: string; hint?: string }) { const { t } = usePortal(); const uniqueId = useId(); const id = props.id || `${props.name}-${uniqueId}`; return <div className="field"><label htmlFor={id}>{t(label)}{props.required && <span className="required" aria-hidden="true"> *</span>}</label><input {...props} id={id} aria-describedby={hint ? `${id}-hint` : undefined} />{hint && <small id={`${id}-hint`}>{t(hint)}</small>}</div>; }
export function Textarea({ label, hint, ...props }: TextareaHTMLAttributes<HTMLTextAreaElement> & { label: string; hint?: string }) { const { t } = usePortal(); const uniqueId = useId(); const id = props.id || `${props.name}-${uniqueId}`; return <div className="field"><label htmlFor={id}>{t(label)}{props.required && <span className="required" aria-hidden="true"> *</span>}</label><textarea rows={4} {...props} id={id} aria-describedby={hint ? `${id}-hint` : undefined} />{hint && <small id={`${id}-hint`}>{t(hint)}</small>}</div>; }
export function Select({ label, children, ...props }: SelectHTMLAttributes<HTMLSelectElement> & { label: string; children: ReactNode }) { const { t } = usePortal(); const uniqueId = useId(); const id = props.id || `${props.name}-${uniqueId}`; return <div className="field"><label htmlFor={id}>{t(label)}{props.required && <span className="required" aria-hidden="true"> *</span>}</label><select {...props} id={id}>{children}</select></div>; }

export function MutationForm({ children, submit, onSubmit, onDone, reset = false, className = "" }: { children: ReactNode; submit: string; onSubmit: (data: FormData) => Promise<unknown>; onDone?: () => void; reset?: boolean; className?: string }) {
  const { t } = usePortal(); const [pending, setPending] = useState(false); const [error, setError] = useState<string>(); const [saved, setSaved] = useState(false); const errorRef = useRef<HTMLDivElement>(null);
  return <form className={`form-stack ${className}`} onInvalidCapture={e => { const target = e.target as HTMLInputElement; if (target.setCustomValidity) target.setCustomValidity(t("check_field")); }} onInputCapture={e => { const target = e.target as HTMLInputElement; if (target.setCustomValidity) target.setCustomValidity(""); }} onSubmit={async e => {
    e.preventDefault(); if (pending) return; const form = e.currentTarget; const data = new FormData(form); setPending(true); setError(undefined); setSaved(false);
    try { await onSubmit(data); setSaved(true); if (reset) form.reset(); onDone?.(); }
    catch (e) { setError(e instanceof ApiError ? e.code : "network_error"); setTimeout(() => errorRef.current?.focus(), 0); }
    finally { setPending(false); }
  }}><fieldset disabled={pending}>{children}</fieldset>{error && <div tabIndex={-1} ref={errorRef}><ErrorBox code={error} /></div>}{saved && <p className="success-text" role="status"><CheckCircle aria-hidden="true" />{t("saved")}</p>}<button className="button primary" disabled={pending} type="submit">{t(pending ? "saving" : submit)}{!pending && <ArrowRight size={18} aria-hidden="true" />}</button></form>;
}
export function ActionButton({ children, action, onDone, variant = "secondary" }: { children: ReactNode; action: () => Promise<unknown>; onDone?: () => void; variant?: string }) {
  const [pending, setPending] = useState(false); const [error, setError] = useState<string>(); const { t } = usePortal();
  return <div className="action-wrap"><button type="button" className={`button ${variant}`} disabled={pending} onClick={async () => { setPending(true); setError(undefined); try { await action(); onDone?.(); } catch (e) { setError(e instanceof ApiError ? e.code : "network_error"); } finally { setPending(false); } }}>{pending ? t("saving") : children}</button>{error && <ErrorBox code={error} />}</div>;
}
export function Panel({ title, hint, children, action, id }: { title: string; hint?: string; children: ReactNode; action?: ReactNode; id?: string }) { const { t } = usePortal(); const anchor = id || ({ review: "review", assign: "assign", assignment: "assignment", proposal: "proposal", milestones: "milestones", outcome: "outcome", evidence: "evidence", original_report: "original-report" } as Record<string, string>)[title]; return <section className="panel" id={anchor} tabIndex={anchor ? -1 : undefined}><span id={anchor === "outcome" ? "feedback" : undefined} className="panel-anchor" aria-hidden="true" /><div className="panel-heading"><div><h2>{t(title)}</h2>{hint && <p>{t(hint)}</p>}</div>{action}</div>{children}</section>; }
export function DateText({ value }: { value: string }) { const { lang } = usePortal(); return <time dateTime={value}>{new Intl.DateTimeFormat(lang === "hi" ? "hi-IN" : "en-IN", { day: "numeric", month: "short", year: "numeric" }).format(new Date(value))}</time>; }
export function Money({ value }: { value: number }) { const { lang } = usePortal(); return <>{new Intl.NumberFormat(lang === "hi" ? "hi-IN" : "en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value)}</>; }
export function ChallengeCard({ challenge: c, privateView = false }: { challenge: Challenge; privateView?: boolean }) {
  const { t, lang } = usePortal();
  return <Link className={`challenge-card domain-${c.domain}`} href={privateView ? `/workspace/challenges/${c.id}` : `/challenges/${c.id}`}><div className="card-top"><span className="domain-icon"><DomainIcon domain={c.domain} /></span><Badge value={c.status} /></div><span className="domain-label">{t(c.domain)}</span><h3>{privateView && c.title ? c.title : lang === "hi" ? c.public_title_hi : c.public_title_en}</h3><p className="card-summary">{privateView && !c.summary_en ? c.description : lang === "hi" ? c.summary_hi : c.summary_en}</p><div className="card-bottom"><span><MapPin size={15} aria-hidden="true" />{t(c.district)}</span><ArrowUpRight size={20} aria-label={t("view_challenge")} /></div></Link>;
}
export function Progress({ status }: { status: string }) { const { t } = usePortal(); const stages = ["submitted", "validated", "assigned", "in_progress", "validation", "resolved"]; const current = stages.indexOf(status); const previous = useRef(status); const [advanced, setAdvanced] = useState(false); useEffect(() => { if (previous.current === status) return; previous.current = status; setAdvanced(true); const timer = window.setTimeout(() => setAdvanced(false), 420); return () => window.clearTimeout(timer); }, [status]); return <ol className="progress-list" aria-label={t("progress")}>{stages.map((stage, i) => <li key={stage} className={`${i <= current ? "reached" : ""}${advanced && i === current ? " advanced" : ""}`} aria-current={i === current ? "step" : undefined}><span className="progress-number">{i < current ? <CheckCircle size={18} weight="fill" aria-hidden="true" /> : i + 1}</span>{t(stage)}</li>)}</ol>; }
export function formObject(data: FormData) { return Object.fromEntries(data.entries()) as Record<string, string>; }
